# Generated by Django 5.2.6 on 2026-01-29 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0003_playlistprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='capa',
            field=models.ImageField(blank=True, null=True, upload_to='capas_playlists/'),
        ),
    ]
