# Generated by Django 5.2.6 on 2026-02-16 21:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0004_playlist_capa'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='favoritos',
            field=models.ManyToManyField(blank=True, related_name='playlists_favoritas', to=settings.AUTH_USER_MODEL),
        ),
    ]
