# Generated by Django 5.2.6 on 2026-02-21 19:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0005_playlist_favoritos'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Musica',
            new_name='Song',
        ),
        migrations.RenameField(
            model_name='playlist',
            old_name='nome',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='playlist',
            old_name='musicas',
            new_name='songs',
        ),
        migrations.RenameField(
            model_name='playlistprogress',
            old_name='ultima_atualizacao',
            new_name='last_update',
        ),
        migrations.RenameField(
            model_name='playlistprogress',
            old_name='segundos_assistidos',
            new_name='seconds_watched',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='artista',
            new_name='artist',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='titulo',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='playlist',
            name='capa',
        ),
        migrations.RemoveField(
            model_name='playlist',
            name='favoritos',
        ),
        migrations.AddField(
            model_name='playlist',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='playlist_covers/'),
        ),
        migrations.AddField(
            model_name='playlist',
            name='favorites',
            field=models.ManyToManyField(blank=True, related_name='favorite_playlists', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='PlaylistRating',
        ),
    ]
