# Generated by Django 5.2.6 on 2026-02-21 20:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0006_rename_musica_song_rename_nome_playlist_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Song',
            new_name='Musica',
        ),
        migrations.RenameField(
            model_name='musica',
            old_name='artist',
            new_name='artista',
        ),
        migrations.RenameField(
            model_name='musica',
            old_name='title',
            new_name='titulo',
        ),
        migrations.RenameField(
            model_name='playlist',
            old_name='songs',
            new_name='musicas',
        ),
        migrations.RenameField(
            model_name='playlist',
            old_name='name',
            new_name='nome',
        ),
        migrations.RenameField(
            model_name='playlistprogress',
            old_name='seconds_watched',
            new_name='segundos_assistidos',
        ),
        migrations.RenameField(
            model_name='playlistprogress',
            old_name='last_update',
            new_name='ultima_atualizacao',
        ),
        migrations.RemoveField(
            model_name='playlist',
            name='cover',
        ),
        migrations.RemoveField(
            model_name='playlist',
            name='favorites',
        ),
        migrations.AddField(
            model_name='playlist',
            name='capa',
            field=models.ImageField(blank=True, null=True, upload_to='capas_playlists/'),
        ),
        migrations.AddField(
            model_name='playlist',
            name='favoritos',
            field=models.ManyToManyField(blank=True, related_name='playlists_favoritas', to=settings.AUTH_USER_MODEL),
        ),
    ]
