# Generated by Django 5.2.6 on 2025-10-12 21:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Amizade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, 'Pendente'), (1, 'Aceita'), (2, 'Recusada')], default=0, verbose_name='Status')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes_enviadas', to=settings.AUTH_USER_MODEL, verbose_name='De')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes_recebidas', to=settings.AUTH_USER_MODEL, verbose_name='Para')),
            ],
            options={
                'verbose_name': 'Amizade',
                'verbose_name_plural': 'Amizades',
                'unique_together': {('from_user', 'to_user')},
            },
        ),
    ]
